/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SourcePriority =
  | "xfa_xml"
  | "widget_geometry"
  | "acroform"
  | "layout"
  | "ocr"
  | "heuristic"
  | "reviewer_override";

export interface FormDefinition {
  id: string;
  title: string;
  documentClass: "xfa_backed_fillable" | "acroform_only" | "born_digital_nonfillable" | "scanned_image_heavy" | "mixed";
  reviewStatus: "draft" | "needs_review" | "reviewed" | "accepted";
  sourcePriority: SourcePriority[];
  sourceConflicts: string[];
  pages: PageNode[];
  issues: ExtractionIssue[];
  metadata: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
export interface PageNode {
  id: string;
  orderIndex: number;
  label: string;
  sections: SectionNode[];
  evidence?: EvidenceAnchor[];
  [k: string]: unknown;
}
export interface SectionNode {
  id: string;
  orderIndex: number;
  title: string;
  description?: string;
  pageId: string;
  lineage: string[];
  groups: GroupNode[];
  fields: FieldNode[];
  [k: string]: unknown;
}
export interface GroupNode {
  id: string;
  orderIndex: number;
  label: string;
  description?: string;
  pageId: string;
  sectionId: string;
  lineage: string[];
  sourceCoordinates: Coordinates[];
  evidence: EvidenceAnchor[];
  fields: FieldNode[];
  rendererHints: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
export interface Coordinates {
  page: number;
  x: number;
  y: number;
  width: number;
  height: number;
  [k: string]: unknown;
}
export interface EvidenceAnchor {
  anchorId: string;
  sourcePriority: SourcePriority;
  page: number;
  snippet: string;
  bounds?: Coordinates;
  confidence: number;
  notes?: string;
  [k: string]: unknown;
}
export interface FieldNode {
  id: string;
  stableKey: string;
  orderIndex: number;
  lineage: string[];
  pageId: string;
  sectionId: string;
  semanticType:
    | "text"
    | "textarea"
    | "select"
    | "radio"
    | "checkbox"
    | "date"
    | "number"
    | "phone"
    | "email"
    | "signature_attestation"
    | "repeatable_group"
    | "statement";
  label: string;
  helpText?: string;
  required: boolean;
  sourceCoordinates: Coordinates[];
  evidence: EvidenceAnchor[];
  confidence: number;
  sourcePriority: SourcePriority[];
  sourceConflicts: string[];
  reviewStatus: "draft" | "needs_review" | "reviewed" | "accepted";
  options: ChoiceOption[];
  validations: ValidationRule[];
  conditionals: ConditionalRule[];
  rendererHints: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
export interface ChoiceOption {
  value: string;
  label: string;
  orderIndex: number;
  selectedByDefault: boolean;
  evidence: EvidenceAnchor[];
  [k: string]: unknown;
}
export interface ValidationRule {
  ruleId: string;
  ruleType: "required" | "regex" | "min" | "max" | "length" | "custom";
  message: string;
  value?: string | number | null;
  [k: string]: unknown;
}
export interface ConditionalRule {
  ruleId: string;
  whenFieldId: string;
  operator: "equals" | "not_equals" | "contains" | "exists";
  expectedValue?: string;
  effect: "show" | "hide" | "require" | "disable";
  enabled?: boolean;
  [k: string]: unknown;
}
export interface ExtractionIssue {
  code:
    | "xfa_visual_mismatch"
    | "ambiguous_field_type"
    | "label_mismatch"
    | "duplicate_node"
    | "orphaned_node"
    | "page_flow_order_conflict"
    | "learned_heuristic_application"
    | "treatment_mapping_proposal";
  severity: "info" | "warning" | "error";
  message: string;
  nodeId?: string;
  evidenceAnchorIds: string[];
  confidenceBand: "high" | "medium" | "low";
  suggestedAction?: string;
  [k: string]: unknown;
}
